### ISSUE TITLE
Reproduce baseX ntcir11 results

### ISSUE THREAD

**Issue by physikerwelt** [TU-Berlin/mathosphere#93]
Check that
https://github.com/TU-Berlin/mathosphere/tree/master/basex#steps-performed-for-the-submission
works.
I currently get the following error:
```
/tmp/baseX/basex$ time java -Xmx12G -jar basex-0.0.1-SNAPSHOT-j                                                                                                                                                             ar-with-dependencies.jar -d /tmp/baseX/data -q NTCIR11-Math-mathQueries-particip                                                                                                                                                             ants.xml -o ./results.csv -c
BaseX 8.2 [Server]
Server was started (port: 1984)
IO Error: /tmp/baseX/data (Is a directory)
java.io.FileNotFoundException: /tmp/baseX/data (Is a directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at com.formulasearchengine.mathosphere.basex.Server.startup(Server.java:                                                                                                                                                             68)
        at com.formulasearchengine.mathosphere.basex.Benchmark.run(Benchmark.jav                                                                                                                                                             a:110)
        at com.formulasearchengine.mathosphere.basex.Benchmark.main(Benchmark.ja                                                                                                                                                             va:83)

```

**Comment by physikerwelt** [comment]
I suggest the following
[ ] update mvn dependency to the lastes baseX version
[ ] commit (check that all tests still work fine)
[ ] read baseX documentation and figure out how a directory can be read.
[ ] Adjust https://github.com/TU-Berlin/mathosphere/blob/master/basex/src/main/java/com/formulasearchengine/mathosphere/basex/Server.java#L68 with an if statement that checks if the argument is a file or a directory
[ ] try to run https://github.com/TU-Berlin/mathosphere/tree/master/basex#steps-performed-for-the-submission
[ ] commit the fix.

**Comment by plato2000** [comment]
There's another issue as well - when I give it just a file instead of a directory, it gives me a BaseX exception on "math.xml". I just gave it the math00000000.xml file from the MWS dump. It has an error when the database is created. I updated the maven dependency to the latest BaseX version. I will now figure out how to give it a directory.

**Comment by physikerwelt** [comment]
> I updated the maven dependency to the latest BaseX version.
Please make a pull request for that;-)

**Comment by physikerwelt** [comment]
I tried it with math00000000.xml and it reports Import completed. Start Monitoring.

**Comment by physikerwelt** [comment]
but the result is not very satisfactory
` cat results.csv
CSV option has been disabled for now. Use https://github.com/physikerwelt/xstlprocJ/blob/master/test/transform.xsl`

**Comment by physikerwelt** [comment]
if I change the output to xml I get the follwing
```
/tmp/baseX/basex$ head results.xml
<?xml version="1.0" encoding="utf-8"?>
<results xmlns="http://ntcir-math.nii.ac.jp/">
  <run runtag="baseX1470067706012" runtime="" run_type="automated">
    <result for="NTCIR11-Math-1" runtime="768897635"/>
    <result for="NTCIR11-Math-2" runtime="590178669">
      <hit id="math.657.24" xref="" score="10" rank="1"/>
    </result>
    <result for="NTCIR11-Math-3" runtime="599178959"/>
    <result for="NTCIR11-Math-4" runtime="574021284">
      <hit id="math.642.67" xref="" score="10" rank="1"/>
```

**Comment by plato2000** [comment]
I also get the "Import completed" message, but a few seconds later, I get a message saying
```
org.basex.core.BaseXException:
concatenated with the contents of the .xml file
java.lang.ArrayIndexOutOfBoundsException: 2048
	at org.basex.core.Command.execute(Command.java:100)
	at org.basex.core.Command.execute(Command.java:122)
```

**Comment by plato2000** [comment]
Okay, so I decided to go through the BaseX tutorials and I realized that in the tutorial, they simply gave the file path to BaseX instead of giving it the contents. I tried this, and it gave me the same error. Then, I decided to use the sample input.xml file they gave, and it worked perfectly there - no errors, and the search on the RestD interface gave a non-null response. I think that the xml files that are in the dump are malformed, and need to be fixed.

**Comment by physikerwelt** [comment]
@plato2000 we need to get the same behavior on our machines... So do you get the same XML file if you use math0000000.xml ?

**Comment by plato2000** [comment]
I'm not sure what you mean, but if I download the file at https://raw.githubusercontent.com/BaseXdb/basex/master/basex-examples/src/main/resources/xml/input.xml, and I give it this file, after changing the Server.java file's startup CreateDB call to `final CreateDB db = new CreateDB(DATABASE_NAME, file.getAbsolutePath());`, instead of reading the file in line by line (on my fork), then if I go to the restd interface and try any xquery, I get a response that is not null and it seems to work without throwing any errors in the console. However, if I use math0000000.xml, I get the same BaseX exception as I mentioned before. I believe that this means that the math xml file is malformed.

**Comment by plato2000** [comment]
@physikerwelt When I run the command you mentioned, I get the same output as you but with more data concatenated to the end. However, this is just with running the basex jar directly. Doesn't restd use the same startup function though? Why does it throw an error when running through restd when it is perfectly fine working with basex directly?

**Comment by physikerwelt** [comment]
Let's fix one problem after the other. The issue we are looking into right now, is to pass an entire directory to baseX. Correct?
The other issue has to do with the restd interface. There is a parameter which defines the files to be read. But lets fix that later.

**Comment by physikerwelt** [comment]
I'm not sure if we can resolve this issue at the moment. I currently do not know how to pass a directory to the basex server. I'll discuss that witht the baseX developers on thrusday, unless you have another idea.

**Comment by physikerwelt** [comment]
I got an email from the basex developers that the second argument can be path.

**Comment by physikerwelt** [comment]
@plato2000 I geth the impression that 14e2b165db704d06f8310e90c6412aec48e138b8 does the job. Do you agree?

**Comment by plato2000** [comment]
@physikerwelt I think you're right. I did a similar thing on my fork but if the second argument can be a path, then yours is more elegant.

**Comment by physikerwelt** [comment]
It works now, but takes slightly longer
`real    11m30.446s
user    11m14.930s
sys     0m28.966s
`

**Comment by physikerwelt** [comment]
after running the tests again with the removed xrefs I get slightly better performance
```
real    9m44.762s
user    9m49.265s
sys     0m16.229s

**Comment by physikerwelt** [comment]
I think this can be closed?
